name: statekit_cli
description: CLI tool for rapidly scaffolding Flutter projects with StateKit architecture and code generation.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

platforms:
  linux:
  macos:
  windows:

environment:
  sdk: ^3.6.1

dependencies:
  dart_console: ^4.1.1
  dart_style: ^3.0.1
  pubspec_parse: ^1.5.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0

executables:
  statekit: